### ISSUE TITLE
Bug: fixed column with rowspan table, the plugin bring the width of narrowest 1st column to use

### ISSUE THREAD

**Issue by xenogew** [wingmeng/fixedThead#3]
Topmost first row and column is `colspan=2`, I prefer that will bring the width of the first cell in the first place.

**Comment by wingmeng** [comment]
@xenogew Please see this demo: https://wingmeng.github.io/fixedThead/test/demo6.html

**Comment by xenogew** [comment]
Now I can solved it, thanks.
