### ISSUE TITLE
大神,能否添加右列固定,或者左右都有列固定的场景

### ISSUE THREAD

**Issue by meihangbo** [wingmeng/fixedThead#4]
大神,能否添加右列固定,或者左右都有列固定的场景,谢谢!

**Comment by wingmeng** [comment]
> 大神,能否添加右列固定,或者左右都有列固定的场景,谢谢!

抱歉，暂时无法提供。类似需求请使用 [Layui](https://github.com/sentsin/layui)

**Comment by meihangbo** [comment]
> > 大神,能否添加右列固定,或者左右都有列固定的场景,谢谢!
> 
> 抱歉，暂时无法提供。类似需求请使用 [Layui](https://github.com/sentsin/layui)
Layui 复杂表头下实现有bug,才找的这个,不过还是谢谢您.
